upstream api_backend {
    server backend:4100;
}

server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass http://api_backend;
    }

    location /uploads/ {
        proxy_pass http://api_backend;
    }
}
